### PR TITLE
Django 1.9 compatibility

### PR DESCRIPTION
**Pull request by simion**
Please merge and make a release in pypi, we need this in production.
Thanks.

### CODE REVIEW

**Comment by vrusinov** [comment]
FYI - there's one more issue in fields.py:

"from django.utils.importlib import import_module" is not possible in 1.9 since django.utils.importlib has been removed. It looks like it can be simply replaced with importlib since it was added to python 2.7 and 3.1

**Comment by simion** [comment]
@vrusinov fixed

**Comment by vrusinov** [comment]
Thanks. I've also sent a pull request for that small thing: #71

Now let's see if author(s) respond and finally merge them.

**Comment by simion** [comment]
Yeah, that would be nice, we need this asap. We use it in production and this is the only package stopping us from upgrading to django 1.9

**Comment by markunsworth** [comment]
@simion Which branch of django are you using? We also want to move to 1.9 but were going to fork django and try and make the necessary changes

**Comment by markunsworth** [comment]
@aburgel you seem to the the most recently active person on this repo (and django/mongodbengine). Are you still active/online? 

Are any of the others nonrel team members still bashing keys regularly? (@adieu @charettes @dartdog @emperorcezar @fhahn @FlaPer87 @gpitfield @gregbayer @Wilfred @wrwrwr )

Would be good to get some input on some of these pull requests and/or add someone who is willing to take up the task of moving this project forwards.

**Comment by aburgel** [comment]
@markunsworth I'm not active on this project anymore. I'm happy to help out if someone wants to take the lead on the project, but unfortunately I don't have much time to commit to this anymore.

**Pull request closed without merging**
