### PR TITLE
_decode_child now leverages the Lookup API

### PR DESCRIPTION
**Pull request by kavdev**
I managed to find the new location for everything except annotations. I tried self.query.get_aggregation(self.connection.alias) but that gave me a recursion error. I'm pretty sure that if an annotation isn't included in the query, it's set to true.

### CODE REVIEW

**Comment by sethdenner** [comment]
Is there a fork of this project that is more active? I would really like to get this library up to date.

**Comment by aburgel** [comment]
@sethdenner this looks like an incomplete pull request. there's code commented out and a comment about not knowing where to pull some data from. if you'd like it to be merged in, you could finish it off.

i would like this to be backwards compatible with previous versions of django if possible. we support 1.4-1.6 right now.

**Comment by sethdenner** [comment]
Awesome! Glad to know someone's listening to this thing.

I'll take over this branch and answer the outstanding questions if this has
been abandoned. This solution is a lot better than the workaround I came up
with to allow Django 1.7.

**Comment by kavdev** [comment]
Hey, sorry for the absence in communication -- I've been swamped the past couple of days. I'll take a look at your changes tomorrow.

If you have any questions about my work, let me know.
________________________________

**Comment by aburgel** [comment]
@kavdev @sethdenner can I close this PR now that #55 is in progress?

**Comment by sethdenner** [comment]
I believe so. I didn't take all of @kavdev's commits. I left out the running 2to3 as it appears there is a sperate pull request and there was a second minor change that didn't seem within the scope of this issue.

**Comment by kavdev** [comment]
Closing in favor of @63.

**Pull request closed without merging**
